#ifdef LNGENG
#define PB_SYM_PSP_UP			"\x80"
#define PB_SYM_PSP_RIGHT		"\x81"
#define PB_SYM_PSP_DOWN			"\x82"
#define PB_SYM_PSP_LEFT			"\x83"
#define PB_SYM_PSP_TRIANGLE		"\x84"
#define PB_SYM_PSP_CIRCLE		"\x85"
#define PB_SYM_PSP_CROSS		"\x86"
#define PB_SYM_PSP_SQUARE		"\x87"
#define PB_SYM_PSP_NOTE			"\x88"
#else
#define PB_SYM_PSP_UP			"↑"
#define PB_SYM_PSP_RIGHT		"→"
#define PB_SYM_PSP_DOWN			"↓"
#define PB_SYM_PSP_LEFT			"←"
#define PB_SYM_PSP_TRIANGLE		"△"
#define PB_SYM_PSP_CIRCLE		"○"
#define PB_SYM_PSP_CROSS		"×"
#define PB_SYM_PSP_SQUARE		"□"
#define PB_SYM_PSP_NOTE			"♪"

#define PPREFSMSG_BOOTMESSAGE " pprefs 起動準備完了! / 起動ボタン:"
#define PPREFSMSG_ADD_TOP " <<追記>> : 追記したいプラグインを選択してください "
#define PPREFSMSG_ADD_HOWTOUSE " %s:選択 HOME:やめる L:フォルダ階層上へ R:フォルダ開く "
#define PPREFSMSG_ADD_HOWTOUSE_2 " %s:選択 HOME:やめる L:フォルダ階層上へ R:フォルダ開く START:現在位置のフォルダを選択 "
#define PPREFSMSG_SUBMENU_LIST "追記","削除","pergame編集","設定","COPY ME"
#define PPREFSMSG_SUBMENU_LIST_GO "追記","削除","pergame編集","設定","eh0:/閲覧"
#define PPREFSMSG_SUBMENU_HOTOUSE " %s:選択 %s:戻る "
#define PPREFSMSG_SUBMENU_TITLE "メニュー"
#define PPREFSMSG_COPYME_ERROR "エラーが発生しました"
#define PPREFSMSG_COPYME_INSERTERROR "pprefsが入っているMSを入れてください"
#define PPREFSMSG_MAINMENU_HOTOUSE "%s選択 △メニュー □+↑/↓並び替え SELECT編集破棄&リロード HOME保存&終了 START保存&VSH再起動"
#define PPREFSMSG_MAINMENU_REPUSHSTART "もう一度STARTを押すと\nRESTART VSH"
#define PPREFSMSG_MAINMENU_RELOAD "編集を破棄して、\nリロードしてもよろしいですか?"
#define PPREFSMSG_YESORNO "%s:はい %s:いいえ"
#define PPREFSMSG_COPYME_FIRSTCONFIRM "\"COPY ME\"を実行する前に現在の編集を保存してください"
#define PPREFSMSG_COPYME_FIRSTCONFIRMHOTOUSE "START:保存して続ける SELECT:編集破棄し続ける\nHOME:\"COPY ME\"をやめる"
#define PPREFSMSG_COPYME_INSERT2NDMS "2枚目のメモリースティックを\n入れてください"
#define PPREFSMSG_COPYME_INSERT2NDMSHOWTOUSE "%s:入れた HOME:コピーやめる"
#define PPREFSMSG_COPYME_DONETOCOPY "コピーが完了しました"
#define PPREFSMSG_COPYME_FAILTOCOPY "正しくコピーできませんでした"
#define PPREFSMSG_FAILTOWRITE "%sの書き込みに失敗しました"
#define PPREFSMSG_FAILTOWRITEHOWTOUSE "%s:リトライ %s:スキップ "
#define PPREFSMSG_EDITPERGAME_SELECTPRX "プラグインを選択してね"
#define PPREFSMSG_EDITPERGAME_SELECTGAME "ゲームを選択してね"
#define PPREFSMSG_EDITPERGAME_HOTOUSE "HOME:やめる START:保存 %s長押:行削除 Lトリガ:最上へ Rトリガ:最下へ"
#define PPREFSMSG_EDITPERGAME_HOTOUSE_2 "→:コメントアウト(#)切替 ←:ブラックリスト(!)切替 □+↑/↓:並び替え(have issues)"
#define PPREFSMSG_EDITPERGAME_TOP "pergame編集β (画面がチカチカしてしまい、申\し訳ありません)"
#define PPREFSMSG_SUBMENU_EH0 "閲覧オンリー / 選択しても何も起きません "
#endif
