all:
	make -f Makefile_pprefs
en:
	make -f Makefile_pprefs LANGUAGE=english
english:
	make en
lite:
	make -f Makefile_pprefs_lite
litejp:
	make -f make -f Makefile_pprefs

clean:
	make -f Makefile_pprefs clean
	make -f Makefile_pprefs_lite clean
