#ifdef LNGENG
#define PB_SYM_PSP_UP			"\x80"
#define PB_SYM_PSP_RIGHT		"\x81"
#define PB_SYM_PSP_DOWN			"\x82"
#define PB_SYM_PSP_LEFT			"\x83"
#define PB_SYM_PSP_TRIANGLE		"\x84"
#define PB_SYM_PSP_CIRCLE		"\x85"
#define PB_SYM_PSP_CROSS		"\x86"
#define PB_SYM_PSP_SQUARE		"\x87"
#define PB_SYM_PSP_NOTE			"\x88"
#else
#define PB_SYM_PSP_UP			"Å™"
#define PB_SYM_PSP_RIGHT		"Å®"
#define PB_SYM_PSP_DOWN			"Å´"
#define PB_SYM_PSP_LEFT			"Å©"
#define PB_SYM_PSP_TRIANGLE		"Å¢"
#define PB_SYM_PSP_CIRCLE		"Åõ"
#define PB_SYM_PSP_CROSS		"Å~"
#define PB_SYM_PSP_SQUARE		"Å†"
#define PB_SYM_PSP_NOTE			"ÅÙ"

#define PTXTMSG_SELECTER_TITLE "Please select text file"
#define PTXTMSG_VIEW_TOP "TEXT"
#define PTXTMSG_VIEW_HOTOUSE "L:Top R:Bottom Å®:NextPage Å©:PrevPage HOME:Exit %s:Back holdÅ†:SpeedUp"
#define PPREFSMSG_ADD_HOWTOUSE " %s:Select HOME:Exit L:UpDir R:OpenDir"
#define PPREFSMSG_ADD_HOWTOUSE_2 "%s:Select HOME:Exit L:UpDir R:OpenDir START:SelectCurrentDir"
#define PPREFSMSG_SELECTBOX_HOTOUSE " %s:Select "
#define PPREFSMSG_SELECTBOX_HOTOUSE_2 " %s:Select HOME:Quit "

#endif
